"""Create requirements dependency file.
"""

import re
import sys

from pathlib import Path


def main(args=sys.argv[1:]):
    "Write Makefile dependencies for requirements."

    print("# Generated by Mkdeps.py -- do not edit!\n")

    for filename in args:
        txtfile = Path(filename).with_suffix(".txt")
        deps = " ".join(dependencies(filename))
        print(f"{txtfile}: {deps}")


def dependencies(reqfile):
    "Yield dependencies of a requirements file."

    yield reqfile
    text = Path(reqfile).read_text()
    for match in re.finditer(r"^-[cr]\s+(\S+)", text, re.M):
        yield match.group(1)


if __name__ == "__main__":
    main()
