# Generated by requirements.py -- do not edit!

requirements-test.txt: requirements-test.in requirements.txt
requirements-dev.txt: requirements-dev.in requirements-test.txt
requirements.txt: requirements.in constraints.txt
