# Generated by requirements.py -- do not edit!

requirements-doc.txt: requirements-doc.in requirements-test.txt
requirements-test.txt: requirements-test.in constraints.txt
requirements-dev.txt: requirements-dev.in requirements-test.txt
requirements.txt: requirements.in requirements-test.txt
