# Generated by Mkdeps.py -- do not edit!

requirements-test.txt: requirements-test.in constraints.txt requirements.txt
requirements-dev.txt: requirements-dev.in constraints.txt requirements.txt
requirements.txt: requirements.in constraints.txt
